spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/cinema_ebooking_db?sslMode=REQUIRED&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update