spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: cinema-ebooking

  profiles:
    active: local  # mặc định chạy local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  # ================== HIKARI CONNECTION POOL ==================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

# ================== LOGGING ==================
logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF